# Generated by Django 4.2.24 on 2025-09-26 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='department',
            new_name='departments',
        ),
    ]
